name: Daily Automated Contributor

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  REPO_NAME_ALT: ${{ vars.REPO_NAME_ALT }}
  REPO_OWNER_ALT: ${{ vars.REPO_OWNER_ALT }}
  
  ENABLE_LOG_BRANCH: ${{ vars.ENABLE_LOG_BRANCH }}
  LOG_BRANCH: ${{ vars.LOG_BRANCH }}
  NEWS_DIR: ${{ vars.NEWS_DIR }}
  REMOTE_UPSTREAM: ${{ vars.REMOTE_UPSTREAM }}

  FORK_OWNER: ${{ github.repository_owner }}

jobs:
  contribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Bot Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and gh CLI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Clone fork repository (work repo)
        run: |
          # REPO_NAME_ALT y REPO_OWNER_ALT se leen de las nuevas variables env
          git clone https://${{ secrets.GH_PAT_PRINCIPAL }}@github.com/${{ env.FORK_OWNER }}/${{ env.REPO_NAME_ALT }}.git ${{ env.REPO_NAME_ALT }}
          cd ${{ env.REPO_NAME_ALT }}
          git remote add upstream https://github.com/${{ env.REPO_OWNER_ALT }}/${{ env.REPO_NAME_ALT }}.git || true
        env:
          GH_PAT_PRINCIPAL: ${{ secrets.GH_PAT_PRINCIPAL }}

      - name: Run contributor (generate content, commit & push)
        run: |
          cd ${{ env.REPO_NAME_ALT }}
          python ../main.py
        env:
          FORK_PATH: .
          
      - name: Create Pull Request using gh
        id: create_pr
        run: |
          BRANCH_NAME=$(cat ${{ env.REPO_NAME_ALT }}/branch_name.txt)
          # Authenticate gh
          echo "${{ secrets.GH_PAT_PRINCIPAL }}" | gh auth login --with-token
          # Create PR from fork_owner:branch -> repo_owner:main
          gh pr create \
            --base main \
            --head "${{ env.FORK_OWNER }}:${BRANCH_NAME}" \
            --repo "${{ env.REPO_OWNER_ALT }}/${{ env.REPO_NAME_ALT }}" \
            --title "feat: Daily news digest (${BRANCH_NAME})" \
            --body "Automated daily digest generated by daily-contributor-bot."
          echo "pr_created=true" >> $GITHUB_OUTPUT
        env:
          GH_PAT_PRINCIPAL: ${{ secrets.GH_PAT_PRINCIPAL }}